// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_C_HdFhAdxK15kExe0r6kdBVOnX9Rdn0',
    appId: '1:379469730951:web:408745a2e52112cb531422',
    messagingSenderId: '379469730951',
    projectId: 'multstore-fa449',
    authDomain: 'multstore-fa449.firebaseapp.com',
    storageBucket: 'multstore-fa449.appspot.com',
    measurementId: 'G-K3PKN4THGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65eeWFviZFCVrKrn9L1rwE1juCjH4Hhk',
    appId: '1:379469730951:android:4c0a600f1fb97e8f531422',
    messagingSenderId: '379469730951',
    projectId: 'multstore-fa449',
    storageBucket: 'multstore-fa449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQw8L9q2bg8DLxvTx1grxs0ZvdxvfOIU',
    appId: '1:379469730951:ios:d3af8d54ccbff2e5531422',
    messagingSenderId: '379469730951',
    projectId: 'multstore-fa449',
    storageBucket: 'multstore-fa449.appspot.com',
    iosClientId: '379469730951-cmpbkuboa325821cc3mrt6dmclepntnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.multStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQw8L9q2bg8DLxvTx1grxs0ZvdxvfOIU',
    appId: '1:379469730951:ios:b20f7d9e9b6fc6a0531422',
    messagingSenderId: '379469730951',
    projectId: 'multstore-fa449',
    storageBucket: 'multstore-fa449.appspot.com',
    iosClientId: '379469730951-r6a9hn8hj7lc2bd6mbh8tnmm5vsab9fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.multStore.RunnerTests',
  );
}
